/**
 * FavoriteLocation entity class for the Room database.
 * This class represents a table for storing favorite locations with latitude, longitude, and solar noon.
 * Author: Oliver Kadvany - 041096826
 * Lab Section: 031
 * Creation Date: 2024-03-31
 */

package algonquin.cst2335.lian0122.Sun;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Entity class for storing favorite locations in the Room database.
 * Represents a table with latitude, longitude, and an autogenerated ID.
 */
@Entity(tableName = "favorite_locations")
public class FavoriteLocation {

    /**
     * Primary key for the FavoriteLocation entity, auto-generated.
     */
    @PrimaryKey(autoGenerate = true)
    public int id;

    /**
     * Latitude of the favorite location.
     */
    public double latitude;

    /**
     * Longitude of the favorite location.
     */
    public double longitude;

    /**
     * Constructs a FavoriteLocation instance with specified latitude and longitude.
     * @param latitude Latitude of the favorite location.
     * @param longitude Longitude of the favorite location.
     */
    public FavoriteLocation(double latitude, double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }
}
